spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect